# Copyright 2025 Zaxxon
name: 'Build Swweeep Magicrobots'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["swweeep_left nice_view_adapter nice_view", "swweeep_right nice_view_adapter nice_view"]'
      custom_config: |
        ["#define U_BTN1 &mkp MB2
        #define U_BTN2 &mkp MB3
        #define U_BTN3 &mkp MB1"]
      kconfig: |
        ["CONFIG_ZMK_POINTING=y
        CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
        CONFIG_ZMK_SLEEP=y
        CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000"]
